# Importing Libraries

In [117]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing Dataset

In [118]:
cropreq=pd.read_csv('croprequirements.csv') # d

In [119]:
cropreq.head()

,Crop,Suitability,Texture,pH,Slope,Slope_per,Slope_code,Erosion,Erosion_code,Gravel_code,Rocky_code,Drainage,Drainage_code,Depth,Depth_per,Depth_code,LCC,Temperature,Rainfall,LGP
0,Castor,S1,"l,scl,sil,cl,sl",6.5-7.5,"level to nearly level, very gently sloping",<3,"A,B",slight erosion,A,A,A,well drained,A,"mod deep,deep,very deep",75-200,"A,B,C",1,26-32,600-750,110-150
1,Castor,S2,"sicl,sic,sc,c",6.4-5.0,gently sloping,3 to 5,C,moderate erosion,B,B,B,moderately well drained,A,moderately shallow,50-75,C,2,33-35,400-600,120-150
2,Castor,S3,"ls,c",8.1-9.0,moderately sloping,5 to 10,D,severe erosion,C,C,C,"poorly drained,excessively drained",C,shallow,25-50,E,3,36-40,250-400,90-120
3,Castor,N,s,9.0-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,very shallow,0-25,F,5,>40,250-400,0-90
4,Groundnut,S1,"ls,sl,sil,l,scl,cl,sicl",6.0-8.0,"level to nearly level, very gently sloping",<3,"A,B",slight erosion,A,A,A,well drained,A,"mod deep,deep,very deep",75-200,"A,B,C",1,24-30,700-1000,NaN

In [120]:
crop_names=cropreq['Crop'].unique()
crop_names

array(['Castor', 'Groundnut', 'Ragi', 'Rice', 'Sugarcane'], dtype=object)

In [121]:
group_crop=cropreq.groupby('Crop')
eachcrop=[]
for i in crop_names:
    eachcrop.append(group_crop.get_group(i))

In [122]:
eachcrop[0]

,Crop,Suitability,Texture,pH,Slope,Slope_per,Slope_code,Erosion,Erosion_code,Gravel_code,Rocky_code,Drainage,Drainage_code,Depth,Depth_per,Depth_code,LCC,Temperature,Rainfall,LGP
0,Castor,S1,"l,scl,sil,cl,sl",6.5-7.5,"level to nearly level, very gently sloping",<3,"A,B",slight erosion,A,A,A,well drained,A,"mod deep,deep,very deep",75-200,"A,B,C",1,26-32,600-750,110-150
1,Castor,S2,"sicl,sic,sc,c",6.4-5.0,gently sloping,3 to 5,C,moderate erosion,B,B,B,moderately well drained,A,moderately shallow,50-75,C,2,33-35,400-600,120-150
2,Castor,S3,"ls,c",8.1-9.0,moderately sloping,5 to 10,D,severe erosion,C,C,C,"poorly drained,excessively drained",C,shallow,25-50,E,3,36-40,250-400,90-120
3,Castor,N,s,9.0-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,very shallow,0-25,F,5,>40,250-400,0-90

In [123]:
cropreqnew=cropreq['Crop'].astype('category').to_frame()

In [124]:
cropreqnew=cropreqnew.join(cropreq['Suitability'].astype('category'))

In [125]:
cropreqnew

         Crop Suitability
0      Castor          S1
1      Castor          S2
2      Castor          S3
3      Castor           N
4   Groundnut          S1
5   Groundnut          S2
6   Groundnut          S3
7   Groundnut           N
8        Ragi          S1
9        Ragi          S2
10       Ragi          S3
11       Ragi           N
12       Rice          S1
13       Rice          S2
14       Rice          S3
15       Rice           N
16  Sugarcane          S1
17  Sugarcane          S2
18  Sugarcane          S3
19  Sugarcane           N

In [141]:
cropreqnew=cropreqnew.join(cropreq['Texture'])
cleaned = cropreqnew.Texture.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='g').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [170]:
cropreqnew=cropreqnew.join(cropreq['Slope_code'])
cleaned = cropreqnew.Slope_code.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='g').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [ ]:
cropreqnew=cropreqnew.join(cropreq['Drainage_code'])
cleaned = cropreqnew.Drainage_code.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='gd').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [180]:
cropreqnew=cropreqnew.join(cropreq['Erosion_code'])
cleaned = cropreqnew.Erosion_code.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='ge').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [182]:
cropreqnew=cropreqnew.join(cropreq['Gravel_code'])
cleaned = cropreqnew.Gravel_code.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='gg').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [183]:
cropreqnew=cropreqnew.join(cropreq['Depth_code'])
cleaned = cropreqnew.Depth_code.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='gde').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [ ]:
cropreqnew=cropreqnew.join(cropreq['Rocky_code'])
cleaned = cropreqnew.Rocky_code.str.split(',', expand=True).stack()
a=pd.get_dummies(cleaned,prefix='gr').groupby(level=0).sum()
cropreqnew=cropreqnew.join(a)

In [186]:
cropreqnew

,Crop,Suitability,Texture,g_c,g_cl,g_l,g_ls,g_s,g_sc,g_scl,...,gde_A,gde_B,gde_C,gde_D,gde_E,gde_F,Rocky_code,gr_A,gr_B,gr_C
0,Castor,S1,"l,scl,sil,cl,sl",0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1,1,1,0,0,0,A,1.0,0.0,0.0
1,Castor,S2,"sicl,sic,sc,c",1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,1,0,0,0,B,0.0,1.0,0.0
2,Castor,S3,"ls,c",1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,1,0,C,0.0,0.0,1.0
3,Castor,N,s,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,1,NaN,NaN,NaN,NaN
4,Groundnut,S1,"ls,sl,sil,l,scl,cl,sicl",0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,1,1,1,0,0,0,A,1.0,0.0,0.0
5,Groundnut,S2,"cl,sicl,scl,sc,sic,c",1.0,1.0,0.0,0.0,0.0,1.0,1.0,...,0,0,0,1,0,0,B,0.0,1.0,0.0
6,Groundnut,S3,"c,sic,s,ls,sl",1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0,0,0,0,1,0,C,0.0,0.0,1.0
7,Groundnut,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,1,NaN,NaN,NaN,NaN
8,Ragi,S1,"l,sil,sl,cl,sicl,scl",0.0,1.0,1.0,0.0,0.0,0.0,1.0,...,1,1,1,0,0,0,A,1.0,0.0,0.0
9,Ragi,S2,"sic,c,sc",1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,1,0,0,B,0.0,1.0,0.0
10,Ragi,S3,"ls,s,c",1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0,0,0,0,1,0,C,0.0,0.0,1.0
11,Ragi,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,1,NaN,NaN,NaN,NaN
12,Rice,S1,"c,sic,cl,sicl,sc",1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,1,1,1,0,0,0,A,1.0,0.0,0.0
13,Rice,S2,"scl,sil,l",0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0,0,0,1,0,0,A,1.0,0.0,0.0
14,Rice,S3,"sl,ls",0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,0,0,1,0,B,0.0,1.0,0.0
15,Rice,N,s,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0,0,0,0,0,1,C,0.0,0.0,1.0
16,Sugarcane,S1,"l,cl,sil,sicl",0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1,1,0,0,0,0,A,1.0,0.0,0.0
17,Sugarcane,S2,"sl,ls",0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0,0,1,0,0,0,B,0.0,1.0,0.0
18,Sugarcane,S3,c,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,1,0,0,C,0.0,0.0,1.0
19,Sugarcane,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,1,1,NaN,NaN,NaN,NaN

In [189]:
cropreqnew=cropreqnew.join(cropreq[['pH','LCC','Temperature','Rainfall','LGP']])

In [190]:
cropreqnew.to_csv('cropreq_updated.csv')